version: '3.2'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
    - ./backend:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "XDG_CONFIG_HOME=/app"
    ports:
    - "8080:80"
    links:
      - php-fpm
      - node-backend

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    links:
      - mysql
      - node-backend

  php-cli:
    build:
      context: ./docker/php-cli
      dockerfile: Dockerfile
    volumes:
    - ./backend:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "COMPOSER_MEMORY_LIMIT=-1"
    links:
      - mysql
    tty: true

  mysql:
    image: mysql:8.0
    volumes:
    - database:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=laravel"
    ports:
    - "33061:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=secret
      - UPLOAD_LIMIT=64M
    restart: always
    ports:
      - 8081:80
  node-backend:
    image: node:18-alpine
    ports:
        - "3000:3000"
    volumes:
    - ./backend:/var/www
    working_dir: /var/www
    tty: true

  node-frontend:
    image: node:22-alpine
    volumes:
      - ./frontend:/var/www
    working_dir: /var/www
    tty: true

volumes:
  database:
    
